global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus.yml'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'checkout-payment-service'
    static_configs:
      - targets: ['host.docker.internal:8080']